// Bilingual question bank + UI strings, ported from the prototype.

export const TR = {
  en: {
    logo: "Tanasub",
    heroBadge: "Two people. One private link. No accounts.",
    heroTitle1: "Understand each other",
    heroTitleEm: "more",
    heroTitle2: "",
    heroSub: "Discover personalities, lifestyles, communication styles, and conversation starters. No compatibility scores. No judgment. Just better conversations.",
    startSession: "Start a session",
    noAccount: "No account required",
    noContact: "No phone or email",
    anonymous: "Fully anonymous",
    private: "Fully private, just between you two",
    footerPrivacy: "Only people with your session link can ever see your report.",
    codeLabel: "Session code",
    copy: "Copy", copied: "Copied",
    shareWhatsapp: "Share via WhatsApp",
    continue: "Continue",
    createTitle: "Your private session is ready",
    createSub: "Share this link with the other person. Your answers stay private until you're both done.",
    youAre: "You (Person A)", personB: "Person B",
    whatCallYou: "What should we call you?",
    nicknameSub: "A nickname is perfect — Coffee Lover, Blue Falcon, whatever feels like you.",
    nicknamePlaceholder: "Nickname",
    begin: "Begin the questionnaire",
    next: "Next", finish: "Finish",
    textPlaceholder: "Type freely — this one's just for you two.",
    answeringAs: "Answering as",
    doneTitle: "is done.",
    waitingSub: "Your report unlocks the moment the second person finishes.\nIn this preview, hand the device over — or send them the link.",
    continueAsB: "Continue as Person B",
    reportUnlocked: "Report unlocked",
    reportSub: "No score. No verdict. Just what you learned about each other.",
    inCommon: "What you have in common",
    topicsTitle: "Topics worth discussing",
    topicsEmpty: "You lined up closely across the board — talk about why that is.",
    startersTitle: "Conversation starters",
    greenFlagsTitle: "Green flags",
    footerNote: "This report is private to your session link.",
    langToggle: "العربية",
    sectionLabels: { personality: "Personality", lifestyle: "Lifestyle", values: "Values", fun: "Fun", short: "In your words" },
  },
  ar: {
    logo: "تناسُب",
    heroBadge: "شخصان. رابط خاص واحد. بدون حسابات.",
    heroTitle1: "افهما بعضكما",
    heroTitleEm: "أكثر",
    heroTitle2: "",
    heroSub: "اكتشفا الشخصيات، أنماط الحياة، أسلوب التواصل، ومواضيع للنقاش. بدون نسب توافق. بدون أحكام. فقط محادثات أعمق.",
    startSession: "ابدأ جلسة",
    noAccount: "بدون تسجيل حساب",
    noContact: "بدون رقم جوال أو إيميل",
    anonymous: "مجهول تمامًا",
    private: "خاص تمامًا، بينكما فقط",
    footerPrivacy: "فقط من يملك رابط الجلسة يمكنه رؤية تقريركما.",
    codeLabel: "رمز الجلسة",
    copy: "نسخ", copied: "تم النسخ",
    shareWhatsapp: "مشاركة عبر واتساب",
    continue: "متابعة",
    createTitle: "جلستك الخاصة جاهزة",
    createSub: "شارك هذا الرابط مع الشخص الآخر. تبقى إجاباتكما خاصة حتى ينتهي كلاكما.",
    youAre: "أنت (الشخص الأول)", personB: "الشخص الثاني",
    whatCallYou: "بماذا نناديك؟",
    nicknameSub: "اسم مستعار يكفي تمامًا — عاشق القهوة، الصقر الأزرق، أو أي اسم يشبهك.",
    nicknamePlaceholder: "الاسم المستعار",
    begin: "ابدأ الأسئلة",
    next: "التالي", finish: "إنهاء",
    textPlaceholder: "اكتب بحرية — هذا السؤال بينكما فقط.",
    answeringAs: "تجيب باسم",
    doneTitle: "انتهى.",
    waitingSub: "يُفتح التقرير بمجرد انتهاء الشخص الثاني.\nفي هذه المعاينة، مرّر الجهاز — أو أرسل له الرابط.",
    continueAsB: "متابعة كالشخص الثاني",
    reportUnlocked: "تم فتح التقرير",
    reportSub: "بدون نسبة. بدون حكم. فقط ما تعلمتماه عن بعضكما.",
    inCommon: "ما تشتركان فيه",
    topicsTitle: "مواضيع تستحق النقاش",
    topicsEmpty: "إجاباتكما متقاربة إلى حد كبير — تحدثا عن السبب.",
    startersTitle: "أفكار لبدء الحديث",
    greenFlagsTitle: "نقاط إيجابية",
    footerNote: "هذا التقرير خاص برابط جلستكما فقط.",
    langToggle: "English",
    sectionLabels: { personality: "الشخصية", lifestyle: "نمط الحياة", values: "القيم", fun: "للمرح", short: "بكلماتكما" },
  },
};

export type QuestionOption = { label: string; label_ar: string; tags: string[] };
export type Question = {
  id: string;
  section: "personality" | "lifestyle" | "values" | "fun" | "short";
  prompt: string;
  prompt_ar: string;
  type?: "text";
  options?: QuestionOption[];
};

export const QUESTIONS: Question[] = [
  { id: "p1", section: "personality",
    prompt: "It's Friday night. What are you doing?", prompt_ar: "ليلة جمعة. وش تسوي؟",
    options: [
      { label: "Inviting everyone over", label_ar: "أدعو الكل عندي", tags: ["Social", "Warm"] },
      { label: "Dinner with close friends", label_ar: "عشاء مع أقرب الأصدقاء", tags: ["Warm", "Selective"] },
      { label: "Staying home, no plans", label_ar: "قاعد بالبيت، بدون خطط", tags: ["Calm", "Independent"] },
      { label: "Going for a drive, just because", label_ar: "طلعة سيارة بدون سبب", tags: ["Adventurous", "Independent"] },
    ]},
  { id: "p2", section: "personality",
    prompt: "Plans get cancelled last minute. Your honest reaction?", prompt_ar: "انلغت الخطة بآخر لحظة. رد فعلك الصادق؟",
    options: [
      { label: "Great, more time for me", label_ar: "حلو، وقت أكثر لنفسي", tags: ["Calm", "Independent"] },
      { label: "Slightly disappointed", label_ar: "منزعج شوي", tags: ["Warm", "Planner"] },
      { label: "I immediately make new plans", label_ar: "أرتب خطة جديدة فورًا", tags: ["Adventurous", "Social"] },
      { label: "Finally, some quiet", label_ar: "أخيرًا وقت هدوء", tags: ["Calm", "Thoughtful"] },
    ]},
  { id: "p3", section: "personality",
    prompt: "When you're making a big decision, you...", prompt_ar: "لما تتخذ قرار مهم، وش تسوي؟",
    options: [
      { label: "Make a list and weigh every option", label_ar: "أسوي قائمة وأوازن كل خيار", tags: ["Planner", "Goal-driven"] },
      { label: "Go with your gut", label_ar: "أتبع إحساسي", tags: ["Adventurous", "Independent"] },
      { label: "Talk it through with people you trust", label_ar: "أستشير ناس أثق فيهم", tags: ["Warm", "Thoughtful"] },
      { label: "Sleep on it for a few days", label_ar: "أعطي القرار كم يوم", tags: ["Calm", "Reliable"] },
    ]},
  { id: "p4", section: "personality",
    prompt: "A friend needs to vent. You're most likely to...", prompt_ar: "صديق يبغى يفضفض. الأغلب تسوي وش؟",
    options: [
      { label: "Just listen, no advice needed", label_ar: "بس أسمع، بدون نصائح", tags: ["Thoughtful", "Warm"] },
      { label: "Help them find a solution", label_ar: "أساعده يلقى حل", tags: ["Goal-driven", "Reliable"] },
      { label: "Distract them with something fun", label_ar: "ألهيه بشي ممتع", tags: ["Adventurous", "Social"] },
      { label: "Sit with them in comfortable silence", label_ar: "أجلس معه بصمت مريح", tags: ["Calm", "Thoughtful"] },
    ]},
  { id: "p5", section: "personality",
    prompt: "Your ideal Sunday morning starts with...", prompt_ar: "صباح الأحد المثالي يبدأ بـ...",
    options: [
      { label: "An early walk before the world wakes up", label_ar: "مشي مبكر قبل ما يصحى الكل", tags: ["Planner", "Calm"] },
      { label: "Sleeping in, no alarms", label_ar: "نوم زيادة بدون منبه", tags: ["Independent", "Calm"] },
      { label: "Making a big breakfast for everyone", label_ar: "فطور كبير للجميع", tags: ["Family-oriented", "Warm"] },
      { label: "Already halfway through a to-do list", label_ar: "منجز نص المهام", tags: ["Goal-driven", "Planner"] },
    ]},
  { id: "p6", section: "personality",
    prompt: "New environment, new people. You...", prompt_ar: "بيئة جديدة، ناس جدد. تسوي وش؟",
    options: [
      { label: "Introduce yourself to everyone", label_ar: "أعرّف نفسي للجميع", tags: ["Social", "Adventurous"] },
      { label: "Find one person and talk deeply", label_ar: "ألقى شخص وأتكلم معه بعمق", tags: ["Thoughtful", "Warm"] },
      { label: "Observe first, engage later", label_ar: "أراقب أول، وبعدين أتفاعل", tags: ["Calm", "Independent"] },
      { label: "Look for something useful to do", label_ar: "أدوّر شي مفيد أسويه", tags: ["Goal-driven", "Reliable"] },
    ]},
  { id: "p7", section: "personality",
    prompt: "A trip is being planned. Your role is usually...", prompt_ar: "يخططون لرحلة. دورك عادة يكون...",
    options: [
      { label: "The one with the spreadsheet", label_ar: "صاحب جدول التنظيم", tags: ["Planner", "Goal-driven"] },
      { label: "The one who says 'let's just go'", label_ar: "اللي يقول 'خلنا نطلع بس'", tags: ["Adventurous", "Independent"] },
      { label: "The one keeping everyone happy", label_ar: "اللي يخلي الكل مبسوط", tags: ["Warm", "Family-oriented"] },
      { label: "The one who researches every detail quietly", label_ar: "اللي يبحث كل التفاصيل بهدوء", tags: ["Thoughtful", "Reliable"] },
    ]},
  { id: "p8", section: "personality",
    prompt: "What people usually notice about you first?", prompt_ar: "أول شي يلاحظه الناس فيك؟",
    options: [
      { label: "How calm you stay under pressure", label_ar: "هدوئي تحت الضغط", tags: ["Calm", "Reliable"] },
      { label: "How curious you are about everything", label_ar: "فضولي تجاه كل شي", tags: ["Curious", "Adventurous"] },
      { label: "How warm you make people feel", label_ar: "دفئي مع الناس", tags: ["Warm", "Family-oriented"] },
      { label: "How focused you are on your goals", label_ar: "تركيزي على أهدافي", tags: ["Goal-driven", "Planner"] },
    ]},

  { id: "l1", section: "lifestyle",
    prompt: "Morning person or night person?", prompt_ar: "شخص صباحي ولا مسائي؟",
    options: [
      { label: "Up with the sun", label_ar: "أصحى مع الشمس", tags: ["Morning"] },
      { label: "Most alive after 10pm", label_ar: "نشاطي بعد الساعة ١٠", tags: ["Night"] },
      { label: "Somewhere in between", label_ar: "بين بين", tags: ["Flexible"] },
    ]},
  { id: "l2", section: "lifestyle",
    prompt: "Coffee or tea?", prompt_ar: "قهوة ولا شاي؟",
    options: [
      { label: "Coffee, non-negotiable", label_ar: "قهوة، ما فيها نقاش", tags: ["Coffee"] },
      { label: "Tea, always", label_ar: "شاي دائمًا", tags: ["Tea"] },
      { label: "Depends on the day", label_ar: "يعتمد على اليوم", tags: ["Flexible"] },
    ]},
  { id: "l3", section: "lifestyle",
    prompt: "Your home is usually...", prompt_ar: "بيتك عادة...",
    options: [
      { label: "Everything has its place", label_ar: "كل شي بمكانه", tags: ["Organized"] },
      { label: "Lived-in and a little chaotic", label_ar: "معاش فيه وشوي فوضوي", tags: ["Relaxed"] },
      { label: "Tidy in the visible areas only", label_ar: "مرتب بالأماكن الظاهرة بس", tags: ["Balanced"] },
    ]},
  { id: "l4", section: "lifestyle",
    prompt: "How do you feel about hosting guests at home?", prompt_ar: "وش رأيك باستضافة ضيوف بالبيت؟",
    options: [
      { label: "Love it, the more the better", label_ar: "أحبها، وكل ما زاد العدد أحلى", tags: ["Hosts often"] },
      { label: "Small gatherings, occasionally", label_ar: "تجمعات صغيرة بين فترة وأخرى", tags: ["Hosts sometimes"] },
      { label: "Prefer meeting outside the house", label_ar: "أفضل نلتقي برا البيت", tags: ["Hosts rarely"] },
    ]},
  { id: "l5", section: "lifestyle",
    prompt: "Living close to family after marriage feels...", prompt_ar: "السكن قريب من العائلة بعد الزواج يعني لك...",
    options: [
      { label: "Important to me", label_ar: "مهم بالنسبة لي", tags: ["Near family"] },
      { label: "Nice, but not essential", label_ar: "حلو، بس مو ضروري", tags: ["Flexible on distance"] },
      { label: "I'd prefer some distance", label_ar: "أفضل شوي بعد", tags: ["Independent living"] },
    ]},
  { id: "l6", section: "lifestyle",
    prompt: "Money habits, honestly?", prompt_ar: "بصراحة، عاداتك المالية؟",
    options: [
      { label: "I track every riyal", label_ar: "أتابع كل ريال", tags: ["Careful spender"] },
      { label: "I save first, spend what's left", label_ar: "أوفر أول، وأصرف اللي يفضل", tags: ["Saver"] },
      { label: "I spend on what makes life good now", label_ar: "أصرف على اللي يخلي حياتي حلوة الحين", tags: ["Present-focused spender"] },
    ]},

  { id: "v1", section: "values",
    prompt: "When there's a disagreement, you tend to...", prompt_ar: "عند وجود خلاف، غالبًا تسوي...",
    options: [
      { label: "Address it right away", label_ar: "أناقشه فورًا", tags: ["Direct conflict style"] },
      { label: "Take space, then talk", label_ar: "آخذ مساحة، وبعدين نتكلم", tags: ["Reflective conflict style"] },
      { label: "Look for the compromise fast", label_ar: "أدوّر حل وسط بسرعة", tags: ["Accommodating conflict style"] },
    ]},
  { id: "v2", section: "values",
    prompt: "How do you prefer to communicate day-to-day?", prompt_ar: "كيف تفضل التواصل يوميًا؟",
    options: [
      { label: "Long, detailed conversations", label_ar: "محادثات طويلة ومفصّلة", tags: ["Deep communicator"] },
      { label: "Short check-ins throughout the day", label_ar: "رسائل قصيرة خلال اليوم", tags: ["Frequent communicator"] },
      { label: "Quality time over words", label_ar: "وقت نوعي أهم من الكلام", tags: ["Presence-focused communicator"] },
    ]},
  { id: "v3", section: "values",
    prompt: "Career vs. family time — how do you think about the balance?", prompt_ar: "العمل مقابل وقت العائلة — كيف توازن بينهم؟",
    options: [
      { label: "Career ambition matters a lot to me", label_ar: "طموحي المهني مهم جدًا لي", tags: ["Career-driven"] },
      { label: "Family time comes first, always", label_ar: "وقت العائلة أولوية دائمًا", tags: ["Family-first"] },
      { label: "I want both to grow together", label_ar: "أبغى الاثنين ينمون مع بعض", tags: ["Balance-seeking"] },
    ]},
  { id: "v4", section: "values",
    prompt: "What does success mean to you, mostly?", prompt_ar: "وش يعني لك النجاح غالبًا؟",
    options: [
      { label: "Financial security and stability", label_ar: "استقرار مالي وأمان", tags: ["Security-focused"] },
      { label: "Feeling fulfilled in daily life", label_ar: "الشعور بالرضا باليوميات", tags: ["Fulfillment-focused"] },
      { label: "Building something that lasts", label_ar: "بناء شي يدوم", tags: ["Legacy-focused"] },
    ]},
  { id: "v5", section: "values",
    prompt: "How do you feel about moving cities for the right opportunity?", prompt_ar: "وش رأيك بالانتقال لمدينة ثانية لفرصة مناسبة؟",
    options: [
      { label: "I'd move in a heartbeat", label_ar: "أنتقل فورًا", tags: ["Open to relocating"] },
      { label: "Only for something big", label_ar: "بس إذا الفرصة كبيرة", tags: ["Cautiously open to relocating"] },
      { label: "I'd rather stay rooted", label_ar: "أفضل أبقى مكاني", tags: ["Prefers staying put"] },
    ]},

  { id: "f1", section: "fun",
    prompt: "Dream vacation, no budget limit?", prompt_ar: "رحلة الأحلام، بدون حدود ميزانية؟",
    options: [
      { label: "A quiet cabin, nowhere near wifi", label_ar: "كوخ هادئ بعيد عن الواي فاي", tags: ["Nature getaway"] },
      { label: "A city I've never explored", label_ar: "مدينة ما زرتها قبل", tags: ["City explorer"] },
      { label: "Somewhere with really good food", label_ar: "مكان أكله لذيذ جدًا", tags: ["Food traveler"] },
      { label: "A beach, and nothing to do", label_ar: "شاطئ، وبدون أي شي أسويه", tags: ["Beach relaxer"] },
    ]},
  { id: "f2", section: "fun",
    prompt: "How do you feel most appreciated?", prompt_ar: "متى تحس إنك مقدَّر أكثر؟",
    options: [
      { label: "Kind words, said often", label_ar: "كلام لطيف ومتكرر", tags: ["Words of affirmation"] },
      { label: "Someone showing up for me", label_ar: "شخص يكون موجود لأجلي", tags: ["Acts of service"] },
      { label: "Undivided time together", label_ar: "وقت كامل مع بعض", tags: ["Quality time"] },
      { label: "Small, thoughtful gifts", label_ar: "هدايا صغيرة ومدروسة", tags: ["Gifts"] },
    ]},
  { id: "f3", section: "fun",
    prompt: "Pick a season that feels like 'you'", prompt_ar: "اختر فصل يشبهك",
    options: [
      { label: "Spring", label_ar: "الربيع", tags: ["Spring"] },
      { label: "Summer", label_ar: "الصيف", tags: ["Summer"] },
      { label: "Autumn", label_ar: "الخريف", tags: ["Autumn"] },
      { label: "Winter", label_ar: "الشتاء", tags: ["Winter"] },
    ]},
  { id: "f4", section: "fun",
    prompt: "A genuine pet peeve of yours?", prompt_ar: "شي يضايقك بصراحة؟",
    options: [
      { label: "Lateness", label_ar: "التأخير", tags: ["Dislikes lateness"] },
      { label: "Being interrupted", label_ar: "مقاطعتي وأنا أتكلم", tags: ["Dislikes interruptions"] },
      { label: "Messiness", label_ar: "الفوضى", tags: ["Dislikes mess"] },
      { label: "Cancelled plans", label_ar: "إلغاء الخطط", tags: ["Dislikes cancelled plans"] },
    ]},

  { id: "s1", section: "short", type: "text",
    prompt: "My perfect Saturday looks like...", prompt_ar: "يوم سبتي المثالي يكون..." },
  { id: "s2", section: "short", type: "text",
    prompt: "One thing people often misunderstand about me...", prompt_ar: "شي واحد الناس غالبًا يفهمونه غلط عني..." },
  { id: "s3", section: "short", type: "text",
    prompt: "When I'm stressed, what helps most is...", prompt_ar: "لما أكون متوتر، اللي يساعدني أكثر..." },
];
